import Link from "next/link";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import UniLogo from "@/components/uni-logo";

import "@/styles/globals.css";

const workSansFont = Work_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSansFont.className}>
        <nav aria-label="Site navbar" id="navbar">
          <ul id="links" aria-label="List of links for the navigation">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
            <li>
              <Link href="/help">Need help</Link>
            </li>
          </ul>
          <UniLogo />
        </nav>
        {children}
      </body>
      <script
        src="https://www.google.com/recaptcha/api.js"
        async
        defer
      ></script>
    </html>
  );
}
